// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_stack_vertical(t,e,n){function i(e,n,i,o,s){t.support.transform&&t.support.transition?(n.transform||(n.transform=""),n.top&&(n.transform+=" translate3d(0,"+(n.top?n.top:0)+"px,0)"),delete n.top,n.transition=i+"ms all "+o+"ms cubic-bezier(0.770, 0.000, 0.175, 1.000)",e.css(n),s&&e.on("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",s)):i?e.animate(n,i,"easeInOutExpo",s):e.css(n)}var o=jQuery,s=o(this),a=o("li",n),r=o("<div>").addClass("ws_effect").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(n.parent());this.go=function(d,p,f,h){var u=(d-p+1)%a.length;Math.abs(h)>=1&&(u=h>0?0:1),u=!!u^!!t.revers;var c=(t.revers?1:-1)*n.height();a.each(function(t){u&&t!=p&&(this.style.zIndex=Math.max(0,this.style.zIndex-1))});var l=o(".ws_list",n),v=o("<div>").css({position:"absolute",left:0,top:0,width:"100%",height:"100%",overflow:"hidden",zIndex:4}).append(o(e.get(u?d:p)).clone()),g=o("<div>").css({position:"absolute",left:0,top:0,width:"100%",height:"100%",overflow:"hidden",zIndex:4}).append(o(e.get(u?p:d)).clone());t.responsive<3&&(v.find("img").css("width","100%"),g.find("img").css("width","100%")),i(v,{top:u?c:0}),i(g,{top:u?0:.5*-c}),u?(g.appendTo(r),v.appendTo(r)):(v.insertAfter(l),g.insertAfter(l)),u?t.fadeOut&&l.fadeOut(t.duration):(l.stop(!0,!0).hide().css({left:-d+"00%"}),t.fadeOut?l.fadeIn(t.duration):l.show()),setTimeout(function(){i(v,{top:u?0:c},t.duration,t.duration*(u?0:.1),function(){s.trigger("effectEnd"),v.remove(),g.remove()}),i(g,{top:(u?1:0)*n.height()*.5},t.duration,t.duration*(u?.1:0))},0)}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
wowReInitor(jQuery("#wowslider-container1"),{effect:"stack_vertical",prev:"",next:"",duration:20*100,delay:26*100,width:960,height:360,autoPlay:true,playPause:false,stopOnHover:false,loop:false,bullets:true,caption:true,captionEffect:"slide",controls:true,onBeforeStep:0,images:0});